/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shlTest_12 (
    input clk,
    input rst,
    input button,
    output reg [15:0] out,
    output reg [7:0] checkoff,
    output reg [0:0] flag,
    output reg [15:0] s
  );
  
  
  
  wire [16-1:0] M_shift_s;
  reg [16-1:0] M_shift_x;
  reg [16-1:0] M_shift_y;
  reg [6-1:0] M_shift_op;
  shifter16_18 shift (
    .x(M_shift_x),
    .y(M_shift_y),
    .op(M_shift_op),
    .s(M_shift_s)
  );
  
  wire [1-1:0] M_edge_detector_out;
  reg [1-1:0] M_edge_detector_in;
  edge_detector_9 edge_detector (
    .clk(clk),
    .in(M_edge_detector_in),
    .out(M_edge_detector_out)
  );
  reg [7:0] M_checkoff_reg_d, M_checkoff_reg_q = 1'h0;
  reg [0:0] M_flag_reg_d, M_flag_reg_q = 1'h0;
  reg [15:0] M_s_reg_d, M_s_reg_q = 1'h0;
  localparam START_testCase = 3'd0;
  localparam LS1_testCase = 3'd1;
  localparam LS2_testCase = 3'd2;
  localparam LS4_testCase = 3'd3;
  localparam LS8_testCase = 3'd4;
  localparam ERR00_testCase = 3'd5;
  localparam END_testCase = 3'd6;
  localparam ERROR_STATE_testCase = 3'd7;
  
  reg [2:0] M_testCase_d, M_testCase_q = START_testCase;
  
  localparam LS1_X = 16'hf001;
  
  localparam LS1_ALUFN = 6'h20;
  
  localparam LS1_Y = 16'h0001;
  
  localparam LS1_S = 16'he002;
  
  localparam LS2_X = 16'hf001;
  
  localparam LS2_ALUFN = 6'h20;
  
  localparam LS2_Y = 16'h0002;
  
  localparam LS2_S = 16'hc004;
  
  localparam LS4_X = 16'hf001;
  
  localparam LS4_ALUFN = 6'h20;
  
  localparam LS4_Y = 16'h0004;
  
  localparam LS4_S = 16'h0010;
  
  localparam LS8_X = 16'hf001;
  
  localparam LS8_ALUFN = 6'h20;
  
  localparam LS8_Y = 16'h0008;
  
  localparam LS8_S = 16'h0100;
  
  localparam ERR00_X = 16'hf001;
  
  localparam ERR00_ALUFN = 6'h20;
  
  localparam ERR00_Y = 16'h0008;
  
  localparam ERR00_S = 16'h0000;
  
  always @* begin
    M_testCase_d = M_testCase_q;
    M_flag_reg_d = M_flag_reg_q;
    M_s_reg_d = M_s_reg_q;
    M_checkoff_reg_d = M_checkoff_reg_q;
    
    checkoff = M_checkoff_reg_q;
    flag = M_flag_reg_q;
    s = M_s_reg_q;
    out = M_s_reg_q;
    M_shift_x = 1'h0;
    M_shift_y = 1'h0;
    M_shift_op = 1'h0;
    M_edge_detector_in = button;
    
    case (M_testCase_q)
      START_testCase: begin
        M_flag_reg_d = 8'h00;
        M_s_reg_d = 16'h5f71;
        M_checkoff_reg_d = 16'h0000;
        if (M_edge_detector_out == 1'h1) begin
          M_testCase_d = LS1_testCase;
        end
      end
      LS1_testCase: begin
        M_shift_x = 16'hf001;
        M_shift_y = 16'h0001;
        M_shift_op = 6'h20;
        M_checkoff_reg_d[7+0-:1] = 1'h1;
        M_flag_reg_d = (M_shift_s != 16'he002);
        M_s_reg_d = M_shift_s;
        if (M_shift_s == 16'he002) begin
          if (M_edge_detector_out == 1'h1) begin
            M_testCase_d = LS2_testCase;
          end
        end else begin
          M_testCase_d = ERROR_STATE_testCase;
        end
      end
      LS2_testCase: begin
        M_shift_x = 16'hf001;
        M_shift_y = 16'h0002;
        M_shift_op = 6'h20;
        M_checkoff_reg_d[6+0-:1] = 1'h1;
        M_flag_reg_d = (M_shift_s != 16'hc004);
        M_s_reg_d = M_shift_s;
        if (M_shift_s == 16'hc004) begin
          if (M_edge_detector_out == 1'h1) begin
            M_testCase_d = LS4_testCase;
          end
        end else begin
          M_testCase_d = ERROR_STATE_testCase;
        end
      end
      LS4_testCase: begin
        M_shift_x = 16'hf001;
        M_shift_y = 16'h0004;
        M_shift_op = 6'h20;
        M_checkoff_reg_d[5+0-:1] = 1'h1;
        M_flag_reg_d = (M_shift_s != 16'h0010);
        M_s_reg_d = M_shift_s;
        if (M_shift_s == 16'h0010) begin
          if (M_edge_detector_out == 1'h1) begin
            M_testCase_d = LS8_testCase;
          end
        end else begin
          M_testCase_d = ERROR_STATE_testCase;
        end
      end
      LS8_testCase: begin
        M_shift_x = 16'hf001;
        M_shift_y = 16'h0008;
        M_shift_op = 6'h20;
        M_checkoff_reg_d[4+0-:1] = 1'h1;
        M_flag_reg_d = (M_shift_s != 16'h0100);
        M_s_reg_d = M_shift_s;
        if (M_shift_s == 16'h0100) begin
          if (M_edge_detector_out == 1'h1) begin
            M_testCase_d = ERR00_testCase;
          end
        end else begin
          M_testCase_d = ERROR_STATE_testCase;
        end
      end
      ERR00_testCase: begin
        M_shift_x = 16'hf001;
        M_shift_y = 16'h0008;
        M_shift_op = 6'h20;
        M_checkoff_reg_d[3+0-:1] = 1'h1;
        M_flag_reg_d = (M_shift_s != 16'h0000);
        M_s_reg_d = 16'hdead;
        if (M_shift_s == 16'h0000) begin
          if (M_edge_detector_out == 1'h1) begin
            M_testCase_d = END_testCase;
          end
        end else begin
          M_testCase_d = ERROR_STATE_testCase;
        end
      end
      ERROR_STATE_testCase: begin
        if (M_edge_detector_out == 1'h1) begin
          M_testCase_d = END_testCase;
        end
      end
      END_testCase: begin
        M_flag_reg_d = 1'h1;
        M_checkoff_reg_d = 8'hff;
        M_s_reg_d = 16'hc001;
        s = M_s_reg_q;
        flag = M_flag_reg_q;
        checkoff = M_checkoff_reg_q;
        if (M_edge_detector_out == 1'h1) begin
          M_testCase_d = START_testCase;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_flag_reg_q <= 1'h0;
    end else begin
      M_flag_reg_q <= M_flag_reg_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_s_reg_q <= 1'h0;
    end else begin
      M_s_reg_q <= M_s_reg_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_testCase_q <= 1'h0;
    end else begin
      M_testCase_q <= M_testCase_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_checkoff_reg_q <= 1'h0;
    end else begin
      M_checkoff_reg_q <= M_checkoff_reg_d;
    end
  end
  
endmodule
